/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get server timestamps for clock synchronization
         * @description Record the client send and receive times locally and use these server
         *     timestamps to estimate clock offset and round-trip network delay.
         *     No request parameters or body are needed.
         */
        get: operations["timeSync"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        TimeSyncResponse: {
            /**
             * @description Server Unix time in microseconds sampled after detecting the complete
             *     request headers in the read buffer.
             */
            n2: number;
            /**
             * @description Server Unix time in microseconds sampled while constructing the
             *     response, before writing it to the socket. This uses the system wall
             *     clock, so clock adjustments can affect the ordering of timestamps.
             */
            n3: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    timeSync: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /**
             * @description Server timestamps encoded as a JSON object. The current implementation
             *     omits the Content-Type header even though the payload is JSON.
             */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "n2": 1788600000000000,
                     *       "n3": 1788600000000005
                     *     }
                     */
                    "application/json": components["schemas"]["TimeSyncResponse"];
                };
            };
        };
    };
}
