/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/timekeeper/tag": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retreive tags
         * @description Retreives all the tags associated with the user, as well as the default ones
         */
        get: operations["get_tags"];
        put?: never;
        /**
         * Create a tag
         * @description Creates a new tag in the database. The returned tag ID can be used in other endpoints in this service.
         */
        post: operations["create_tag"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/timekeeper/tag/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Modify tag
         * @description Modifies the fields of the tag at the ID
         */
        put: operations["modify_tag"];
        post?: never;
        /**
         * Delete a tag
         * @description Deletes the tag at the given ID. This just marks the tag as deleted, and doesn't actually delete the tag in the database. Timers posted with a deleted tag will still have that tag, the tag just won't appear when querying some endpoints.
         */
        delete: operations["delete_tag"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/timekeeper/time-split": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retreive time splits
         * @description Retrieves all the time splits associated with the user, as well as the default ones
         */
        get: operations["get_time_splits"];
        put?: never;
        /**
         * Create a time split
         * @description Creates a new time split in the database. The returned time split ID can be used in other endpoints in this service. The timer lengths should use the `jiff::Span` format
         */
        post: operations["create_time_split"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/timekeeper/time-split/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Modify a time split
         * @description Modifies the fields of the time split at the ID.
         */
        put: operations["modify_time_split"];
        post?: never;
        /**
         * Delete a time split
         * @description Deletes the time split at the given ID. This just marks the time split as deleted, and doesn't actually delete the time split in the database. Timers posted with a deleted time split will still have that time split, the time split just won't appear when querying some endpoints.
         */
        delete: operations["delete_time_split"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/timekeeper/timer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retreive a timer
         * @description Retreives the most recently started/ended timer if no parameters are specified. Otherwise returns the timers that match the parameters.
         */
        get: operations["get_timers"];
        /**
         * Modify a timer
         * @description This route replaces the fields of the timer at the passed in start time with new fields. When a timer is paused, this route should be used to change the end_timestamp of the timer to the Unix timestamp at which the timer was paused. To resume a timer, a new timer should be posted with the Unix timestamp at which the timer was resumed, and the Unix timestamp in the future at which the remaining time will have elapsed.
         */
        put: operations["modify_timer"];
        /**
         * Post a timer
         * @description Upon starting a new timer, the Unix timestamp of when the timer was started, as well as the Unix timestamp in the future when the timer will end should be sent to this service. The ID of the time split, whether the timer is a work or a break timer, and the tag IDs associated with the timer should also be sent.
         */
        post: operations["post_timer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @example {
         *       "chain": [
         *         "Uh oh!",
         *         "Something happened"
         *       ],
         *       "spantrace": [
         *         {
         *           "fields": "foo=bar this=that",
         *           "file": "crates/schemas/lockinspiel-common-schema/src/error.rs",
         *           "line": 120,
         *           "module_path": "path::to::something",
         *           "name": "thing"
         *         }
         *       ]
         *     }
         */
        EyreErrorWrapper: {
            chain: string[];
            spantrace: components["schemas"]["Frame"][];
        };
        Frame: {
            fields: string;
            file?: string | null;
            /** Format: u-int32 */
            line?: number | null;
            module_path?: string | null;
            name: string;
        };
        /**
         * @example {
         *       "time_split": {
         *         "description": "The certified hood classic",
         *         "name": "Pomodoro"
         *       },
         *       "timers": [
         *         {
         *           "len": "PT25M",
         *           "name": "Work",
         *           "work": true
         *         }
         *       ]
         *     }
         */
        InsertablePackagedTimeSplit: {
            time_split: components["schemas"]["InsertableTimeSplit"];
            timers: components["schemas"]["InsertableTimeSplitTimer"][];
        };
        /**
         * @example {
         *       "name": "Schoolwork"
         *     }
         */
        InsertableTag: {
            name: string;
        };
        /**
         * @example {
         *       "description": "The certified hood classic",
         *       "name": "Pomodoro"
         *     }
         */
        InsertableTimeSplit: {
            description?: string | null;
            name: string;
        };
        /**
         * @example {
         *       "len": "PT25M",
         *       "name": "Work",
         *       "work": true
         *     }
         */
        InsertableTimeSplitTimer: {
            len: components["schemas"]["Interval"];
            name: string;
            work: boolean;
        };
        /**
         * @example {
         *       "end_time": 1788645230399161,
         *       "start_time": 1788641630399161,
         *       "tags": [
         *         54,
         *         45,
         *         78,
         *         23
         *       ],
         *       "time_split_timer": 36
         *     }
         */
        InsertableTimer: {
            end_time: components["schemas"]["Timestamptz"];
            start_time: components["schemas"]["Timestamptz"];
            tags: number[];
            /** Format: int32 */
            time_split_timer: number;
        };
        Interval: string;
        /**
         * @example {
         *       "time_split": {
         *         "description": "The certified hood classic",
         *         "id": 98,
         *         "name": "Pomodoro"
         *       },
         *       "timers": [
         *         {
         *           "id": 35,
         *           "len": "PT25M",
         *           "name": "Work",
         *           "order_idx": 0,
         *           "time_split_id": 989,
         *           "work": true
         *         }
         *       ]
         *     }
         */
        PackagedTimeSplit: {
            time_split: components["schemas"]["TimeSplit"];
            timers: components["schemas"]["TimeSplitTimer"][];
        };
        /**
         * @example {
         *       "id": 78,
         *       "name": "Schoolwork"
         *     }
         */
        Tag: {
            /** Format: int32 */
            id: number;
            name: string;
        };
        /**
         * @example {
         *       "id": 78
         *     }
         */
        TagID: {
            /** Format: int32 */
            id: number;
        };
        /**
         * @example {
         *       "description": "The certified hood classic",
         *       "id": 98,
         *       "name": "Pomodoro"
         *     }
         */
        TimeSplit: {
            description?: string | null;
            /** Format: int32 */
            id: number;
            name: string;
        };
        /**
         * @example {
         *       "time_split_id": 43,
         *       "work": true
         *     }
         */
        TimeSplitData: {
            /** Format: int32 */
            time_split_id: number;
            work: boolean;
        };
        /**
         * @example {
         *       "id": 35,
         *       "len": "PT25M",
         *       "name": "Work",
         *       "order_idx": 0,
         *       "time_split_id": 989,
         *       "work": true
         *     }
         */
        TimeSplitTimer: {
            /** Format: int32 */
            id: number;
            len: components["schemas"]["Interval"];
            name: string;
            /** Format: int32 */
            order_idx: number;
            /** Format: int32 */
            time_split_id: number;
            work: boolean;
        };
        /**
         * @example {
         *       "end_time": 1788645230399166,
         *       "start_time": 1788641630399166,
         *       "tags": [
         *         54,
         *         45,
         *         78,
         *         23
         *       ],
         *       "time_split_data": {
         *         "time_split_id": 43,
         *         "work": true
         *       },
         *       "time_split_timer": 36
         *     }
         */
        Timer: {
            end_time: components["schemas"]["Timestamptz"];
            start_time: components["schemas"]["Timestamptz"];
            tags: (number | null)[];
            time_split_data: components["schemas"]["TimeSplitData"];
            /** Format: int32 */
            time_split_timer?: number | null;
        };
        /**
         * Format: int64
         * @description The returned timestamp is the number of **microseconds** since
         *     the UNIX epoch
         */
        Timestamptz: number;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_tags: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tag"][];
                };
            };
            /** @description It's your fault */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EyreErrorWrapper"];
                };
            };
            /** @description We're having a skill issue */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EyreErrorWrapper"];
                };
            };
        };
    };
    create_tag: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InsertableTag"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagID"];
                };
            };
            /** @description It's your fault */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EyreErrorWrapper"];
                };
            };
            /** @description We're having a skill issue */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EyreErrorWrapper"];
                };
            };
        };
    };
    modify_tag: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InsertableTag"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description It's your fault */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EyreErrorWrapper"];
                };
            };
            /** @description We're having a skill issue */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EyreErrorWrapper"];
                };
            };
        };
    };
    delete_tag: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description It's your fault */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EyreErrorWrapper"];
                };
            };
            /** @description We're having a skill issue */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EyreErrorWrapper"];
                };
            };
        };
    };
    get_time_splits: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PackagedTimeSplit"][];
                };
            };
            /** @description It's your fault */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EyreErrorWrapper"];
                };
            };
            /** @description We're having a skill issue */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EyreErrorWrapper"];
                };
            };
        };
    };
    create_time_split: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InsertablePackagedTimeSplit"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PackagedTimeSplit"];
                };
            };
            /** @description It's your fault */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EyreErrorWrapper"];
                };
            };
            /** @description We're having a skill issue */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EyreErrorWrapper"];
                };
            };
        };
    };
    modify_time_split: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InsertableTimeSplit"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description It's your fault */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EyreErrorWrapper"];
                };
            };
            /** @description We're having a skill issue */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EyreErrorWrapper"];
                };
            };
        };
    };
    delete_time_split: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description It's your fault */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EyreErrorWrapper"];
                };
            };
            /** @description We're having a skill issue */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EyreErrorWrapper"];
                };
            };
        };
    };
    get_timers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Timer"][];
                };
            };
            /** @description It's your fault */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EyreErrorWrapper"];
                };
            };
            /** @description We're having a skill issue */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EyreErrorWrapper"];
                };
            };
        };
    };
    modify_timer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InsertableTimer"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Timer"];
                };
            };
            /** @description It's your fault */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EyreErrorWrapper"];
                };
            };
            /** @description We're having a skill issue */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EyreErrorWrapper"];
                };
            };
        };
    };
    post_timer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InsertableTimer"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Timer"];
                };
            };
            /** @description It's your fault */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EyreErrorWrapper"];
                };
            };
            /** @description We're having a skill issue */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EyreErrorWrapper"];
                };
            };
        };
    };
}
