/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/user/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get profile
         * @description Gets the user profile for the current session
         */
        get: operations["get_profile"];
        /**
         * Update profile
         * @description Updates the user profile for the current session
         */
        put: operations["update_profile"];
        /**
         * Create profile
         * @description Creates a new user profile for the current session
         */
        post: operations["create_profile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/profile/avatar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Replace profile avatar
         * @description Returns the URL that should be used to upload an image of the user's new avatar
         */
        put: operations["put_avatar"];
        post?: never;
        /**
         * Delete profile avatar
         * @description Delete's the user profile's avatar from wherever it is stored
         */
        delete: operations["delete_avatar"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @example {
         *       "chain": [
         *         "Uh oh!",
         *         "Something happened"
         *       ],
         *       "spantrace": [
         *         {
         *           "fields": "foo=bar this=that",
         *           "file": "crates/schemas/lockinspiel-common-schema/src/error.rs",
         *           "line": 120,
         *           "module_path": "path::to::something",
         *           "name": "thing"
         *         }
         *       ]
         *     }
         */
        EyreErrorWrapper: {
            chain: string[];
            spantrace: components["schemas"]["Frame"][];
        };
        Frame: {
            fields: string;
            file?: string | null;
            /** Format: u-int32 */
            line?: number | null;
            module_path?: string | null;
            name: string;
        };
        /**
         * @example {
         *       "bio": "I wonder how Alice and Bob are doing",
         *       "display_name": "John Doe"
         *     }
         */
        InsertableUserProfile: {
            bio: string;
            display_name: string;
        };
        /**
         * @example {
         *       "file_extension": "png"
         *     }
         */
        PutAvatarQuery: {
            file_extension: string;
        };
        UserAvatarPutUrl: {
            url: string;
        };
        /**
         * @example {
         *       "avatar_location": "/user/profile",
         *       "bio": "I wonder how Alice and Bob are doing",
         *       "display_name": "John Doe",
         *       "user_id": "00000000-0000-0000-0000-000000000000"
         *     }
         */
        UserProfile: {
            avatar_location?: string | null;
            bio: string;
            display_name: string;
            /** Format: uuid */
            user_id: string;
        };
        /**
         * @example {
         *       "bio": "I wonder how Alice and Bob are doing",
         *       "display_name": "John Doe"
         *     }
         */
        UserProfileChangeset: {
            bio: string;
            display_name: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_profile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfile"];
                };
            };
            /** @description It's your fault */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EyreErrorWrapper"];
                };
            };
            /** @description We're having a skill issue */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EyreErrorWrapper"];
                };
            };
        };
    };
    update_profile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserProfileChangeset"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description It's your fault */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EyreErrorWrapper"];
                };
            };
            /** @description We're having a skill issue */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EyreErrorWrapper"];
                };
            };
        };
    };
    create_profile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InsertableUserProfile"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description It's your fault */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EyreErrorWrapper"];
                };
            };
            /** @description We're having a skill issue */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EyreErrorWrapper"];
                };
            };
        };
    };
    put_avatar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PutAvatarQuery"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": components["schemas"]["UserAvatarPutUrl"];
                };
            };
            /** @description It's your fault */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EyreErrorWrapper"];
                };
            };
            /** @description We're having a skill issue */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EyreErrorWrapper"];
                };
            };
        };
    };
    delete_avatar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description It's your fault */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EyreErrorWrapper"];
                };
            };
            /** @description We're having a skill issue */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EyreErrorWrapper"];
                };
            };
        };
    };
}
